// Generated by gencpp from file era_task4/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ERA_TASK4_MESSAGE_ADDTWOINTS_H
#define ERA_TASK4_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <era_task4/AddTwoIntsRequest.h>
#include <era_task4/AddTwoIntsResponse.h>


namespace era_task4
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace era_task4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::era_task4::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::era_task4::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::era_task4::AddTwoInts > {
  static const char* value()
  {
    return "era_task4/AddTwoInts";
  }

  static const char* value(const ::era_task4::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::era_task4::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::era_task4::AddTwoInts > 
template<>
struct MD5Sum< ::era_task4::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::era_task4::AddTwoInts >::value();
  }
  static const char* value(const ::era_task4::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::era_task4::AddTwoIntsRequest> should match 
// service_traits::DataType< ::era_task4::AddTwoInts > 
template<>
struct DataType< ::era_task4::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::era_task4::AddTwoInts >::value();
  }
  static const char* value(const ::era_task4::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::era_task4::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::era_task4::AddTwoInts > 
template<>
struct MD5Sum< ::era_task4::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::era_task4::AddTwoInts >::value();
  }
  static const char* value(const ::era_task4::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::era_task4::AddTwoIntsResponse> should match 
// service_traits::DataType< ::era_task4::AddTwoInts > 
template<>
struct DataType< ::era_task4::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::era_task4::AddTwoInts >::value();
  }
  static const char* value(const ::era_task4::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ERA_TASK4_MESSAGE_ADDTWOINTS_H
