// Generated by gencpp from file fkie_multimaster_msgs/LinkStatesStamped.msg
// DO NOT EDIT!


#ifndef FKIE_MULTIMASTER_MSGS_MESSAGE_LINKSTATESSTAMPED_H
#define FKIE_MULTIMASTER_MSGS_MESSAGE_LINKSTATESSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <fkie_multimaster_msgs/LinkState.h>

namespace fkie_multimaster_msgs
{
template <class ContainerAllocator>
struct LinkStatesStamped_
{
  typedef LinkStatesStamped_<ContainerAllocator> Type;

  LinkStatesStamped_()
    : header()
    , links()  {
    }
  LinkStatesStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , links(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >::other >  _links_type;
  _links_type links;





  typedef boost::shared_ptr< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> const> ConstPtr;

}; // struct LinkStatesStamped_

typedef ::fkie_multimaster_msgs::LinkStatesStamped_<std::allocator<void> > LinkStatesStamped;

typedef boost::shared_ptr< ::fkie_multimaster_msgs::LinkStatesStamped > LinkStatesStampedPtr;
typedef boost::shared_ptr< ::fkie_multimaster_msgs::LinkStatesStamped const> LinkStatesStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fkie_multimaster_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'fkie_multimaster_msgs': ['/home/aaryen/yellow_ws/src/multimaster/fkie_multimaster_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7c41a46488485ec6593097b0cabe904";
  }

  static const char* value(const ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7c41a46488485ecULL;
  static const uint64_t static_value2 = 0x6593097b0cabe904ULL;
};

template<class ContainerAllocator>
struct DataType< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fkie_multimaster_msgs/LinkStatesStamped";
  }

  static const char* value(const ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
fkie_multimaster_msgs/LinkState[] links\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: fkie_multimaster_msgs/LinkState\n\
string destination\n\
float32 quality\n\
";
  }

  static const char* value(const ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.links);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinkStatesStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fkie_multimaster_msgs::LinkStatesStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "links[]" << std::endl;
    for (size_t i = 0; i < v.links.size(); ++i)
    {
      s << indent << "  links[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >::stream(s, indent + "    ", v.links[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FKIE_MULTIMASTER_MSGS_MESSAGE_LINKSTATESSTAMPED_H
