// Generated by gencpp from file fkie_multimaster_msgs/LinkState.msg
// DO NOT EDIT!


#ifndef FKIE_MULTIMASTER_MSGS_MESSAGE_LINKSTATE_H
#define FKIE_MULTIMASTER_MSGS_MESSAGE_LINKSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fkie_multimaster_msgs
{
template <class ContainerAllocator>
struct LinkState_
{
  typedef LinkState_<ContainerAllocator> Type;

  LinkState_()
    : destination()
    , quality(0.0)  {
    }
  LinkState_(const ContainerAllocator& _alloc)
    : destination(_alloc)
    , quality(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _destination_type;
  _destination_type destination;

   typedef float _quality_type;
  _quality_type quality;





  typedef boost::shared_ptr< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> const> ConstPtr;

}; // struct LinkState_

typedef ::fkie_multimaster_msgs::LinkState_<std::allocator<void> > LinkState;

typedef boost::shared_ptr< ::fkie_multimaster_msgs::LinkState > LinkStatePtr;
typedef boost::shared_ptr< ::fkie_multimaster_msgs::LinkState const> LinkStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fkie_multimaster_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'fkie_multimaster_msgs': ['/home/aaryen/yellow_ws/src/multimaster/fkie_multimaster_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3fe0aab52336c0bd0bfea55b131c66e";
  }

  static const char* value(const ::fkie_multimaster_msgs::LinkState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3fe0aab52336c0bULL;
  static const uint64_t static_value2 = 0xd0bfea55b131c66eULL;
};

template<class ContainerAllocator>
struct DataType< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fkie_multimaster_msgs/LinkState";
  }

  static const char* value(const ::fkie_multimaster_msgs::LinkState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string destination\n\
float32 quality\n\
";
  }

  static const char* value(const ::fkie_multimaster_msgs::LinkState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination);
      stream.next(m.quality);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinkState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fkie_multimaster_msgs::LinkState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fkie_multimaster_msgs::LinkState_<ContainerAllocator>& v)
  {
    s << indent << "destination: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.destination);
    s << indent << "quality: ";
    Printer<float>::stream(s, indent + "  ", v.quality);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FKIE_MULTIMASTER_MSGS_MESSAGE_LINKSTATE_H
