// Generated by gencpp from file fkie_multimaster_msgs/ListDescription.msg
// DO NOT EDIT!


#ifndef FKIE_MULTIMASTER_MSGS_MESSAGE_LISTDESCRIPTION_H
#define FKIE_MULTIMASTER_MSGS_MESSAGE_LISTDESCRIPTION_H

#include <ros/service_traits.h>


#include <fkie_multimaster_msgs/ListDescriptionRequest.h>
#include <fkie_multimaster_msgs/ListDescriptionResponse.h>


namespace fkie_multimaster_msgs
{

struct ListDescription
{

typedef ListDescriptionRequest Request;
typedef ListDescriptionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListDescription
} // namespace fkie_multimaster_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fkie_multimaster_msgs::ListDescription > {
  static const char* value()
  {
    return "a36ba5a97ce785b9b964aa015b26332b";
  }

  static const char* value(const ::fkie_multimaster_msgs::ListDescription&) { return value(); }
};

template<>
struct DataType< ::fkie_multimaster_msgs::ListDescription > {
  static const char* value()
  {
    return "fkie_multimaster_msgs/ListDescription";
  }

  static const char* value(const ::fkie_multimaster_msgs::ListDescription&) { return value(); }
};


// service_traits::MD5Sum< ::fkie_multimaster_msgs::ListDescriptionRequest> should match 
// service_traits::MD5Sum< ::fkie_multimaster_msgs::ListDescription > 
template<>
struct MD5Sum< ::fkie_multimaster_msgs::ListDescriptionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fkie_multimaster_msgs::ListDescription >::value();
  }
  static const char* value(const ::fkie_multimaster_msgs::ListDescriptionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fkie_multimaster_msgs::ListDescriptionRequest> should match 
// service_traits::DataType< ::fkie_multimaster_msgs::ListDescription > 
template<>
struct DataType< ::fkie_multimaster_msgs::ListDescriptionRequest>
{
  static const char* value()
  {
    return DataType< ::fkie_multimaster_msgs::ListDescription >::value();
  }
  static const char* value(const ::fkie_multimaster_msgs::ListDescriptionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fkie_multimaster_msgs::ListDescriptionResponse> should match 
// service_traits::MD5Sum< ::fkie_multimaster_msgs::ListDescription > 
template<>
struct MD5Sum< ::fkie_multimaster_msgs::ListDescriptionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fkie_multimaster_msgs::ListDescription >::value();
  }
  static const char* value(const ::fkie_multimaster_msgs::ListDescriptionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fkie_multimaster_msgs::ListDescriptionResponse> should match 
// service_traits::DataType< ::fkie_multimaster_msgs::ListDescription > 
template<>
struct DataType< ::fkie_multimaster_msgs::ListDescriptionResponse>
{
  static const char* value()
  {
    return DataType< ::fkie_multimaster_msgs::ListDescription >::value();
  }
  static const char* value(const ::fkie_multimaster_msgs::ListDescriptionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FKIE_MULTIMASTER_MSGS_MESSAGE_LISTDESCRIPTION_H
