// Generated by gencpp from file fkie_multimaster_msgs/ListDescriptionResponse.msg
// DO NOT EDIT!


#ifndef FKIE_MULTIMASTER_MSGS_MESSAGE_LISTDESCRIPTIONRESPONSE_H
#define FKIE_MULTIMASTER_MSGS_MESSAGE_LISTDESCRIPTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fkie_multimaster_msgs/Capability.h>

namespace fkie_multimaster_msgs
{
template <class ContainerAllocator>
struct ListDescriptionResponse_
{
  typedef ListDescriptionResponse_<ContainerAllocator> Type;

  ListDescriptionResponse_()
    : robot_name()
    , robot_type()
    , robot_images()
    , robot_descr()
    , capabilities()  {
    }
  ListDescriptionResponse_(const ContainerAllocator& _alloc)
    : robot_name(_alloc)
    , robot_type(_alloc)
    , robot_images(_alloc)
    , robot_descr(_alloc)
    , capabilities(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_name_type;
  _robot_name_type robot_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_type_type;
  _robot_type_type robot_type;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _robot_images_type;
  _robot_images_type robot_images;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_descr_type;
  _robot_descr_type robot_descr;

   typedef std::vector< ::fkie_multimaster_msgs::Capability_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fkie_multimaster_msgs::Capability_<ContainerAllocator> >::other >  _capabilities_type;
  _capabilities_type capabilities;





  typedef boost::shared_ptr< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListDescriptionResponse_

typedef ::fkie_multimaster_msgs::ListDescriptionResponse_<std::allocator<void> > ListDescriptionResponse;

typedef boost::shared_ptr< ::fkie_multimaster_msgs::ListDescriptionResponse > ListDescriptionResponsePtr;
typedef boost::shared_ptr< ::fkie_multimaster_msgs::ListDescriptionResponse const> ListDescriptionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace fkie_multimaster_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'fkie_multimaster_msgs': ['/home/aaryen/yellow_ws/src/multimaster/fkie_multimaster_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a36ba5a97ce785b9b964aa015b26332b";
  }

  static const char* value(const ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa36ba5a97ce785b9ULL;
  static const uint64_t static_value2 = 0xb964aa015b26332bULL;
};

template<class ContainerAllocator>
struct DataType< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fkie_multimaster_msgs/ListDescriptionResponse";
  }

  static const char* value(const ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot_name\n\
string robot_type\n\
string[] robot_images\n\
string robot_descr\n\
fkie_multimaster_msgs/Capability[] capabilities\n\
\n\
================================================================================\n\
MSG: fkie_multimaster_msgs/Capability\n\
# the ROS namespace of the capability\n\
string namespace\n\
# the name of the capability\n\
string name\n\
# the type of the capability\n\
string type\n\
# list of the images assigned to the this capability\n\
string[] images\n\
# the description of the capability\n\
string description\n\
# a list of nodes assigned to this group. The nodes are described by full ROS name (with namesspace)\n\
string[] nodes \n\
";
  }

  static const char* value(const ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_name);
      stream.next(m.robot_type);
      stream.next(m.robot_images);
      stream.next(m.robot_descr);
      stream.next(m.capabilities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListDescriptionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fkie_multimaster_msgs::ListDescriptionResponse_<ContainerAllocator>& v)
  {
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_name);
    s << indent << "robot_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_type);
    s << indent << "robot_images[]" << std::endl;
    for (size_t i = 0; i < v.robot_images.size(); ++i)
    {
      s << indent << "  robot_images[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_images[i]);
    }
    s << indent << "robot_descr: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_descr);
    s << indent << "capabilities[]" << std::endl;
    for (size_t i = 0; i < v.capabilities.size(); ++i)
    {
      s << indent << "  capabilities[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fkie_multimaster_msgs::Capability_<ContainerAllocator> >::stream(s, indent + "    ", v.capabilities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FKIE_MULTIMASTER_MSGS_MESSAGE_LISTDESCRIPTIONRESPONSE_H
