// Generated by gencpp from file fkie_multimaster_msgs/ListNodes.msg
// DO NOT EDIT!


#ifndef FKIE_MULTIMASTER_MSGS_MESSAGE_LISTNODES_H
#define FKIE_MULTIMASTER_MSGS_MESSAGE_LISTNODES_H

#include <ros/service_traits.h>


#include <fkie_multimaster_msgs/ListNodesRequest.h>
#include <fkie_multimaster_msgs/ListNodesResponse.h>


namespace fkie_multimaster_msgs
{

struct ListNodes
{

typedef ListNodesRequest Request;
typedef ListNodesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListNodes
} // namespace fkie_multimaster_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fkie_multimaster_msgs::ListNodes > {
  static const char* value()
  {
    return "3d07bfda1268b4f76b16b7ba8a82665d";
  }

  static const char* value(const ::fkie_multimaster_msgs::ListNodes&) { return value(); }
};

template<>
struct DataType< ::fkie_multimaster_msgs::ListNodes > {
  static const char* value()
  {
    return "fkie_multimaster_msgs/ListNodes";
  }

  static const char* value(const ::fkie_multimaster_msgs::ListNodes&) { return value(); }
};


// service_traits::MD5Sum< ::fkie_multimaster_msgs::ListNodesRequest> should match 
// service_traits::MD5Sum< ::fkie_multimaster_msgs::ListNodes > 
template<>
struct MD5Sum< ::fkie_multimaster_msgs::ListNodesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fkie_multimaster_msgs::ListNodes >::value();
  }
  static const char* value(const ::fkie_multimaster_msgs::ListNodesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fkie_multimaster_msgs::ListNodesRequest> should match 
// service_traits::DataType< ::fkie_multimaster_msgs::ListNodes > 
template<>
struct DataType< ::fkie_multimaster_msgs::ListNodesRequest>
{
  static const char* value()
  {
    return DataType< ::fkie_multimaster_msgs::ListNodes >::value();
  }
  static const char* value(const ::fkie_multimaster_msgs::ListNodesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fkie_multimaster_msgs::ListNodesResponse> should match 
// service_traits::MD5Sum< ::fkie_multimaster_msgs::ListNodes > 
template<>
struct MD5Sum< ::fkie_multimaster_msgs::ListNodesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fkie_multimaster_msgs::ListNodes >::value();
  }
  static const char* value(const ::fkie_multimaster_msgs::ListNodesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fkie_multimaster_msgs::ListNodesResponse> should match 
// service_traits::DataType< ::fkie_multimaster_msgs::ListNodes > 
template<>
struct DataType< ::fkie_multimaster_msgs::ListNodesResponse>
{
  static const char* value()
  {
    return DataType< ::fkie_multimaster_msgs::ListNodes >::value();
  }
  static const char* value(const ::fkie_multimaster_msgs::ListNodesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FKIE_MULTIMASTER_MSGS_MESSAGE_LISTNODES_H
